- name: Get latest process-compose release info
  ansible.builtin.uri:
    url: "https://api.github.com/repos/F1bonacc1/process-compose/releases/latest"
    return_content: yes
  register: pc_release
  become: no

- name: Set architecture mapping
  ansible.builtin.set_fact:
    arch_map:
      x86_64: amd64
      aarch64: arm64
      armv7l: arm
    os_name: "linux"
  become: no

- name: Set target architecture
  ansible.builtin.set_fact:
    target_arch: "{{ arch_map[ansible_architecture] | default(ansible_architecture) }}"
  become: no

- name: Find correct asset URL for architecture
  ansible.builtin.set_fact:
    pc_asset_url: "{{ item.browser_download_url }}"
  loop: "{{ pc_release.json.assets }}"
  when: item.name is search('process-compose_' + os_name + '_' + target_arch + '.tar.gz')
  become: no

- name: Create temp directory for process-compose
  ansible.builtin.tempfile:
    state: directory
    suffix: pc_install
  register: pc_tempdir
  become: yes

- name: Download process-compose archive
  ansible.builtin.get_url:
    url: "{{ pc_asset_url }}"
    dest: "{{ pc_tempdir.path }}/process-compose.tar.gz"
    mode: "0644"
  become: yes

- name: Extract process-compose binary
  ansible.builtin.unarchive:
    src: "{{ pc_tempdir.path }}/process-compose.tar.gz"
    dest: "{{ pc_tempdir.path }}"
    remote_src: yes
  become: yes

- name: List files after extraction
  ansible.builtin.command: ls -R "{{ pc_tempdir.path }}"
  register: extracted_files
  changed_when: false
  become: yes

- name: Show contents of temp dir
  ansible.builtin.debug:
    var: extracted_files.stdout_lines

- name: Move process-compose binary to /usr/local/bin
  ansible.builtin.command: >
    mv "{{ pc_tempdir.path }}/process-compose" /usr/local/bin/process-compose
  become: yes

- name: Set executable permissions on process-compose
  ansible.builtin.file:
    path: /usr/local/bin/process-compose
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Remove temp directory
  ansible.builtin.file:
    path: "{{ pc_tempdir.path }}"
    state: absent
  become: yes

- name: Verify process-compose installation
  ansible.builtin.command: process-compose version
  register: pc_version
  changed_when: false
  failed_when: pc_version.rc != 0
  become: no

- name: Display process-compose version
  ansible.builtin.debug:
    msg: "process-compose installed version: {{ pc_version.stdout }}"
  when: pc_version.stdout is defined and pc_version.stdout | length > 0

